development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ontario_development
  pool: 5
  username: ontario
  password: ontario123
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ontario_production
  pool: 5
  username: ontario
  password: ontario123
  host: localhost                  
